/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    customers: Customer;
    categories: Category;
    posts: Post;
    tags: Tag;
    users: User;
  };
  globals: {};
}
export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  phoneNumber?: string;
  dateOfBirth?: string;
  gender?: ("male" | "female")[];
  country?: string;
  state?: string;
  postalCode?: string;
  address?: string;
  nameOfNextKin?: string;
  phoneOfNextKin?: string;
  emailOfNextKin?: string;
  condition?: string;
  bloodPressure?: string;
  bloodSugar?: string;
  hba1cReading?: string;
  bodyMassIndex?: string;
  weight?: string;
  height?: string;
  viewPost?: string[] | Post[];
  likes?: string[] | Post[];
  likeCount?: number;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Post {
  id: string;
  title?: string;
  author?: string | User;
  publishedDate?: string;
  category?: string | Category;
  tags?: string[] | Tag[];
  content?: {
    [k: string]: unknown;
  }[];
  status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface User {
  id: string;
  name?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}
export interface Category {
  id: string;
  name?: string;
  password?: string;
}
export interface Tag {
  id: string;
  name?: string;
  password?: string;
}
